### ISSUE TITLE
20 byte limit on receiving and sending on RPI

### ISSUE THREAD

**Issue by matthiascarlier** [elaInnovation/Bluetooth-Python-Sample#1]
Hello,

My company asked me to test the ELA Blue PUCK T EN12830 for a project. I am using a raspberry pi 4 to try and connect to the device and read its data. 

I used your python examples and they seem to work, except when command or response is more then 20 bytes.
When I need to receive a notification that is longer then 20 bytes, the message is just cut off. When I need to send more then 20 bytes, the message is never aknowleged. 

I tried to manually install the bluetooth driver (BlueZ) and bluePY, but this did not change anything.

Is this something you also came across?

**Comment by elaInnovation** [comment]
@matthiascarlier Thank you for your feedback,

We will try to reproduce your problem and test it on our side with raspberry pi 4. If you have more information about the tag firmware version, it could be helpfull on our side.

**Comment by matthiascarlier** [comment]
@elaInnovation Thank you for the quick reply.

The tag firmware is 2.1.0. I started with the default raspian install, which had BlueZ version 5.5. I installed BluePY using pip.

I tried with the latest version of bluez (5.9), but this gives the same result. I also tried to manually install BluePY, but this did not change anything.

I am always using python 3.7.

Do you think testing with a RPI3 could help?

**Comment by elaInnovation** [comment]
@matthiascarlier we have more information to share with you, sorry for the late answer, but we want to really understand this problem

What we see today is a limitation due to a failure of the negociation of MTU between nordic stack and bluez.
To explain and what we understand, when we send a command, the size of the feedback from the tag is higher than 20 bytes.

Normally when we open the channel between Nordic Stack & bluez on unix, there is a negociation between the two devices to change the size of received buffer on the bluez library to go up to 64 bytes instead of 20 bytes. However, this negociation of MTU seems to failed and the default size retained is only 20 octets (default Size in the Nordic Stack).

We change the size directly in the Stack and move it at 64 octets (in our tags in firmware version 3.0.0 possible on our side). We test it again and see that the answer received on the raspbian works fine (we have all information sended by the tag).

For the moment, we don't found a workaround for raspbian on firmware 210. We known that we don't found this problem on Windows 10, Android or iOS. The only way for the moment is the new version on tags BLE 300 and did not find a workaround on raspbian for 210 firmware version. We will give you more information if we found another workaround.

**Comment by matthiascarlier** [comment]
@elaInnovation Thank you for looking into this.

Is it possible for me to update the tags firmware version? I have access to the ELA Devices manager on IOS.

**Comment by elaInnovation** [comment]
Dear,

I have a discussion with the different teams here at ELA, you have to contact the support : support@elainnovation.com to see with them how to change your tags (according to the availablility of the bluetooth firmware version 3.0.0).

Hope we can help you on this point.

**Comment by matthiascarlier** [comment]
@elaInnovation 

Our contact person said we would receive the new version of the tags as soon as possible. So this will be taken care of.

Could you just give me some more information about what caused the problem and how you solved this? We would like to understand where the problem comes from?

Thank you.
